before_script:
  - apt-get update && curl https://install.meteor.com/ | sh
  - apt-get install sudo curl wget -y

stages:
  - test
  - deploy

test_stage:
  stage: test
  environment: Testing
  script:
    - rm package-lock.json
    - ./create_module.sh testing_module
    - meteor npm install
    - meteor -s settings.json --allow-superuser & sleep 180; kill -INT %+
    - exit 0
  tags:
    - linux

heroku_deploy:
  stage: deploy
  environment: Heroku Deployment
  script:
    - apt-get update -qy
    - apt-get install -yqq ruby ruby-dev nodejs --silent
    - gem install dpl
    - dpl --provider=heroku --app=twiice-production --api-key=$HEROKU_STAGING_API_KEY
  tags:
    - linux